import 'dart:convert';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import 'database.dart';

Future<void> exportRecipePdf(
  MixRecipe recipe, {
  Map<String, String>? pigmentNames,
}) async {
  final pigments =
      (jsonDecode(recipe.pigmentData) as List).cast<Map<String, dynamic>>();
  final swatchColor = PdfColor.fromInt(recipe.colorValue | 0xFF000000);

  final pdf = pw.Document();
  pdf.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.a5,
      margin: const pw.EdgeInsets.all(32),
      build: (context) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              recipe.name,
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Text(
              'ChromaStudio spectral recipe',
              style: const pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey700,
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Container(
              width: 96,
              height: 96,
              decoration: pw.BoxDecoration(
                color: swatchColor,
                border: pw.Border.all(color: PdfColors.grey400),
                borderRadius: pw.BorderRadius.circular(8),
              ),
            ),
            pw.SizedBox(height: 12),
            pw.Text(
              'Lab (D65): L=${recipe.labL.toStringAsFixed(1)} '
              'a=${recipe.labA.toStringAsFixed(1)} '
              'b=${recipe.labB.toStringAsFixed(1)}',
            ),
            pw.SizedBox(height: 20),
            pw.Text(
              'Pigments',
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 8),
            ...pigments.map((p) {
              final id = p['id'] as String;
              final weight = (p['weight'] as num).toDouble();
              final name = pigmentNames?[id] ?? id;
              return pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 6),
                child: pw.Row(
                  children: [
                    pw.Expanded(child: pw.Text(name)),
                    pw.Text('${weight.toStringAsFixed(2)} parts'),
                  ],
                ),
              );
            }),
            if (recipe.notes.isNotEmpty) ...[
              pw.SizedBox(height: 16),
              pw.Text(
                'Notes',
                style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(recipe.notes),
            ],
            pw.Spacer(),
            pw.Text(
              'Generated by ChromaStudio',
              style: const pw.TextStyle(
                fontSize: 9,
                color: PdfColors.grey600,
              ),
            ),
          ],
        );
      },
    ),
  );

  final bytes = await pdf.save();
  final dir = await getTemporaryDirectory();
  final safeName = recipe.name.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
  final file = File('${dir.path}/chromastudio_$safeName.pdf');
  await file.writeAsBytes(bytes);
  await Share.shareXFiles(
    [XFile(file.path, mimeType: 'application/pdf')],
    subject: recipe.name,
  );
}

Future<Map<String, String>> loadPigmentNameMap() async {
  final jsonStr =
      await rootBundle.loadString('assets/pigments/all_pigments.json');
  final list = (jsonDecode(jsonStr) as List).cast<Map<String, dynamic>>();
  return {for (final p in list) p['id'] as String: p['name'] as String};
}

Future<void> exportRecipeJson(
  MixRecipe recipe, {
  Map<String, String>? pigmentNames,
}) async {
  final pigments =
      (jsonDecode(recipe.pigmentData) as List).cast<Map<String, dynamic>>();
  final payload = {
    'format': 'chromastudio-recipe-v1',
    'name': recipe.name,
    'notes': recipe.notes,
    'lab': {'L': recipe.labL, 'a': recipe.labA, 'b': recipe.labB},
    'colorArgb': recipe.colorValue,
    'pigments': pigments
        .map(
          (p) => {
            'id': p['id'],
            'name': pigmentNames?[p['id'] as String] ?? p['id'],
            'weight': (p['weight'] as num).toDouble(),
          },
        )
        .toList(),
    'exportedAt': DateTime.now().toUtc().toIso8601String(),
  };

  final dir = await getTemporaryDirectory();
  final safeName = recipe.name.replaceAll(RegExp(r'[^\w\s-]'), '').trim();
  final file = File('${dir.path}/chromastudio_$safeName.json');
  await file.writeAsString(
    const JsonEncoder.withIndent('  ').convert(payload),
  );
  await Share.shareXFiles(
    [XFile(file.path, mimeType: 'application/json')],
    subject: recipe.name,
  );
}
